version: 0.2

phases:
  pre_build:
    commands:
      - mvn install
  build:
    commands:
      - mvn test

reports:
  junit:
    files:
      - '**/*'
    base-directory: "target/surefire-reports/"
    file-format: 'JunitXML'